# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tom Choi
email: tomdevlpr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My porfolio and personal website to experiment, write, inform, and showcase who I am
  and what I have working on thus far.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tomcdev.com" # the base hostname & protocol for your site
twitter_username: tomjuggler
github_username:  lifejuggler
linkedin_name: Tom (Junghwan) Choi

# Build settings
markdown: kramdown

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']